### ISSUE TITLE
This is not valid theme file

### ISSUE THREAD

**Issue by simonsunx** [eclipse-color-theme/eclipse-color-theme#106]
I installed eclipse 4.2, pdt 3.1.1, rse 3.4 and eclipse-color-themes 0.12.
Then i downloaded some xml-themes from http://eclipsecolorthemes.org.
I tried to import themes using Window -> Preferences -> General -> Appearance -> Color Theme.
Every time i saw 'This is not valid theme file'.

Why did it happend? What can i do?

**Comment by MathieuDreano** [comment]
Hello, 
I got the same issue and solved it, mine had no extra first line.
I just opened the XML in notepad++, saved it with another name (also changed the name of the theme).
Worked. I can't really explain why but it worked. Give it a try

**Comment by nanodan** [comment]
Also have this issue.
