### ISSUE TITLE
Installation Issues on Update Site and Eclipse Marketplace 

### ISSUE THREAD

**Issue by jonahgeorge** [eclipse-color-theme/eclipse-color-theme#222]
While trying to install this plugin I ran into two different issues:

1. The zip file returned by the [update site](http://eclipse-color-theme.github.io/update/eclipse-color-theme-update-site.zip) is empty.
2. The [link](http://eclipse-color-theme.github.com/update/content.xml) that the Eclipse Marketplace is pointing to returns a 404.

As a result, I am unable to install this plugin from any source.

**Comment by paulvi** [comment]
read 

http://eclipse-color-theme.github.io/update/

http://marketplace.eclipse.org/content/eclipse-color-theme/help

**Comment by paulvi** [comment]
Alternative p2 repo is at http://www.nodeclipse.org/updates/color-ide-pack/

**Comment by ypsilon-takai** [comment]
I also tryed to install this plugin with the zip file on the update site and faced the same problem. I looked into the zip file and found it contains unnecessary files and directorys in it.

I extracted it and create new zip file which contains only files and directories in the "update" directory. I successfully installed ths plugin with the new zip file.

**Comment by paulvi** [comment]
@jonahgeorge use `http://eclipse-color-theme.github.io/update/` in Help -> Install new software

@ypsilon-takai yes, the .zip is strange, it has `..` folder in the root

eclipse-color-theme-update-site.zip\..\update\

**Comment by fhd** [comment]
Whoops, that one was messed up indeed, [fixed it](https://github.com/eclipse-color-theme/eclipse-color-theme.github.com/commit/14b99442fce4b2767cb577bd66d9818bc8894db3).
