### ISSUE TITLE
Support RustDT syntax

### ISSUE THREAD

**Issue by AndiDog** [eclipse-color-theme/eclipse-color-theme#234]
Plugin for the Rust programming language: [RustDT](https://rustdt.github.io/) should be supported by a mapping for syntax highlighting.

**Comment by rainysaturday** [comment]
I'm working on this, have something that seems OK, will hopefully make a pull request tomorrow.

**Comment by fhd** [comment]
I've just merged #245 which addresses this, I'll make a release with it soon.
