### ISSUE TITLE
eclipsecolorthemes.org site is broken

### ISSUE THREAD

**Issue by edrik** [eclipse-color-theme/eclipse-color-theme#236]
You can create an initial theme an register but after that nothing. You can't edit or loggin to actually do anything.

Tested on several browsers, apperently th account is created bu you cant stay logged in to it.

**Comment by asinitson** [comment]
Confirming: Firefox 40.0.3, Chromium Version 45.0.2454.85. After registering and cloning existing theme nothing can be done.

**Comment by TeodorKolev** [comment]
That repo is dead

**Comment by fhd** [comment]
Not entirely, but I can't deny there's some truth to that lately, unfortunately :disappointed:

I've gotten several reports about this. The problem is that I do not have access to eclipsecolorthemes.org, only @rogerdudler does. Mind looking into that, Roger?

**Comment by TeodorKolev** [comment]
Man. repo have tons of errors not with status unfixed, but even with no answer

**Comment by kajonas** [comment]
Roger, can you, or fhd, or someone fix this issue (finish developing this feature if it never was really working in the first place).  Or provide me some isolated/limited access, so I can fix it myself.  Considering the size of the eclipse user base, it's surprising this is still broken.

**Comment by albertcarrete** [comment]
Not to dig up old issues but the site is still non-operational. Is there anyone who can take a look at it and fix the login issues?

**Comment by spacekookie** [comment]
The site has been displaying a "We’ll be back soon!" title for several days now.

Is there actually work being done there? When can we expect the site to go back online?

**Comment by fhd** [comment]
As I keep saying, the only person with access is @rogerdudler and I haven't heard from him in a while. Once he resurfaces I'm sure he can bring the site back up quickly.

**Comment by spacekookie** [comment]
Does this mean that @rogerdudler has been gone for almost a year now? Because that's when the issue was opened :/

**Comment by fhd** [comment]
I guess :disappointed: He's quite busy usually. I'll certainly say the same for myself, but I'm trying to keep things somewhat alive on the side. Next time I talk to him I'll see if we can get shared access to that website.

**Comment by fhd** [comment]
It's back! Thanks @rogerdudler!

**Comment by Katharsas** [comment]
It's still as broken as before. You cannot login oredit your themes. Can this be reopened?
