### ISSUE TITLE
Font color not changed after theme selection and editor reload

### ISSUE THREAD

**Issue by typophil** [eclipse-color-theme/eclipse-color-theme#237]
Hello,

Might be related to #55 and/or #214!

The installation went smoothly. But after selecting a theme, it just changes the background color. The Font and Font color is not changed. Restarting Eclipse doesn't help. So actually it's not working for me.

Is this known (and I just didn't find the corresponding issue)? Is there a workaround?

*Eclipse:*

    Eclipse IDE for Java Developers

    Version: Mars Release (4.5.0)
    Build id: 20150621-1200

*Installed Plugins:*

|Name|Version|Id|
|---|---|---    
|Eclipse Color Theme|1.0.0.201410260308|com.github.eclipsecolortheme.feature.feature.group	GitHub|
|Eclipse IDE for Java Developers|4.5.0.20150621-1200|epp.package.java|null|
|GoClipse|0.12.1.v201508251600|goclipse_feature.feature.group|The GoClipse Development Team|
|PyDev for Eclipse|4.3.0.201508182223|org.python.pydev.feature.feature.group|Fabio Zadrozny|
|Pydev Mylyn Integration|0.6.0|org.python.pydev.mylyn.feature.feature.group|Fabio Zadrozny|

*OS:*

    OS X Yosemite
    Version 10.10.5 (14F27)

Greetings,
Phil

**Comment by vitaly-zdanevich** [comment]
I have the same problem
Xubuntu i386 14.04.4, Eclipse Mars 4.5.2
Language: apex - I just installed official plugin for force.com
![eclipse-mars-dark](https://cloud.githubusercontent.com/assets/3514015/15799441/601e5d70-2a65-11e6-8639-80821a1484de.png)

**Comment by fhd** [comment]
Seems like #230 should fix this. I'll make a release with this soon. Please reopen if the issue still occurs with the new release.
