### ISSUE TITLE
Project webpage doesn't work

### ISSUE THREAD

**Issue by zulus** [eclipse-color-theme/eclipse-color-theme#241]
As in subject. Server died.

**Comment by fhd** [comment]
@rogerdudler is the only one who has access, and he's sort of MIA, unfortunately :disappointed:

**Comment by davidbecker** [comment]
Webpage seems to be back

**Comment by reinoudk** [comment]
Webpage now redirects to ```goool.ch```. Any updates / thoughts on what should happen now?

**Comment by wqtty** [comment]
what's wrong with this project?

**Comment by seanmullane** [comment]
It seems that with the website down none of the themes can be applied. Is that right?

**Comment by delebota** [comment]
You can still apply the themes, select and one and hit apply as usual. There just isn't a preview anymore (or whatever was displayed).

**Comment by GizMecano** [comment]
It seems that [the main website of the project](http://www.eclipsecolorthemes.org/) is unreachable since a while now.

Does it exist any plan to put it back online in a near future or can we consider [this site as no longer in use](https://twitter.com/GizMecano/status/748948075381682176)?

Of course, I keep in mind that, in addition to this repository, the plugin has been released [on the Eclipse Market](https://marketplace.eclipse.org/node/27025) (but none of these two websites provide previews of the embedded themes as the project page did before).

**Comment by ngukev** [comment]
Any updates on this?  The eclipse we're using at work doesn't have access to the marketplace.  It'll be nice if someone could link me the .epf files.

**Comment by delebota** [comment]
If you can't access the marketplace, go to https://eclipse-color-theme.github.io/update/ the last link will download a zip file. Extract it and there should be an update folder, inside the update folder there should be a features and a plugins folder. Copy the features and plugins folders into your eclipse folder and restart Eclipse.

**Comment by GizMecano** [comment]
The process given by @delebota above will be useful if the `zip` version of the plugin include all the previews.

Indeed, one of the main problem is that the previews of themes are unavailable in the plugin because the site is broken.

**Comment by olegchir** [comment]
What's going on?

**Comment by tedepstein** [comment]
Does anyone have access to the source code and data (theme definitions) for the eclipsecolorthemes.org website? If the current owner of that domain is MIA, as someone suggested, maybe someone can get the site running on another domain, and redirect the plugin to that site.

**Comment by braindevices** [comment]
still cannot access the theme data (http://eclipsecolorthemes.org), it has been months since it said "will back soon".

**Comment by facundoq** [comment]
A data dump of the eclipse themes would be awesome. I had mine stored in eclipsecolorthemes and can no longer access it.

**Comment by PalHebokEpam** [comment]
Is there a working fork of this so we can use this?

**Comment by fhd** [comment]
It's just the website that's broken, and unfortunately it's closed source and only @rogerdudler can redeploy it. There's no way around waiting for him to fix this on eclipsecolorthemes.org...

**Comment by rubin55** [comment]
What would be involved in writing a preview renderer that is not dependent on the website? I mean: what if we simply make the eclipse-color-theme plugin render a preview of the color scheme selected itself instead of deferring to the website at eclipsecolorthemes.org? This way you would not be confronted with the depressing "will be back soon" *within* the plugin and the plugin would be "freed" from the probably very busy/unresponsive maintainer of eclipsecolorthemes.org.

**Comment by fhd** [comment]
Yeah, that'd certainly fix it and I'd certainly merge a PR with this without letting it bitrot for too long :smile: There's even an old issue for this: #70.

**Comment by RealSkeptic** [comment]
Are we talking about Roger Dudler of Frontify? He's active on [Twitter](https://twitter.com/rogerdudler?lang=en), so it doesn't seem that something evil happened to him. Anybody familiar with him care to contact him (mention at Twitter, perhaps? or LinkedIn in-mail? Supposedly he's not active here) and ask him about the web site? It's been months, and it's really annoying to try to restore a theme blind.

**Comment by tedepstein** [comment]
I sent Roger an InMail a couple of days ago.  No reply yet.

**Comment by xumengyin** [comment]
Unfortunately...

**Comment by Gedweb** [comment]
Maybe deploy website to some other domain and rebuild plugin?

**Comment by tedepstein** [comment]
FYI, I heard back from @rogerdudler last week, and he plans to revive the website.  Hoping he'll get it up and running soon.

**Comment by gizmecano** [comment]
It seems that [the website](http://www.eclipsecolorthemes.org/) is anew online :relaxed:

**Comment by fhd** [comment]
Yup, phew :smile:

**Comment by tedepstein** [comment]
@fhd , great to see that the website is back, but preview is still not working:

![image](https://cloud.githubusercontent.com/assets/692813/19386637/613b3d32-91e3-11e6-9709-45f2731581d1.png)

Should we open a new issue to track that separately?
